federal:
  department_of_labor:
    name: "U.S. Department of Labor"
    base_url: "https://www.dol.gov"
    forms:
      - name: "WH-347"
        title: "Statement of Compliance for Federal and Federally Assisted Construction Projects"
        url: "https://www.dol.gov/agencies/whd/government-contracts/construction"
        form_url: "https://www.dol.gov/sites/dolgov/files/WHD/legacy/files/wh347.pdf"
        instructions_url: "https://www.dol.gov/sites/dolgov/files/WHD/legacy/files/wh347instr.pdf"
        check_frequency: "daily"
        contact_email: "WHDInfo@dol.gov"
        last_updated: null
    contact:
      phone: "1-866-487-9243"
      email: "WHDInfo@dol.gov"

states:
  alabama:
    name: "Alabama Department of Labor"
    abbreviation: "AL"
    base_url: "https://www.labor.alabama.gov"
    prevailing_wage_url: "https://www.labor.alabama.gov/docs/prevailing_wage/"
    forms:
      - name: "AL-PW-001"
        title: "Alabama Certified Payroll Report"
        url: "https://www.labor.alabama.gov/docs/prevailing_wage/"
        check_frequency: "weekly"
        contact_email: "prevailingwage@labor.alabama.gov"
    contact:
      phone: "(334) 242-8055"
      email: "prevailingwage@labor.alabama.gov"

  alaska:
    name: "Alaska Department of Labor and Workforce Development"
    abbreviation: "AK"
    base_url: "https://labor.alaska.gov"
    prevailing_wage_url: "https://labor.alaska.gov/lss/wagedb.htm"
    forms:
      - name: "AK-PW-001"
        title: "Alaska Certified Payroll Report"
        url: "https://labor.alaska.gov/lss/wagedb.htm"
        check_frequency: "weekly"
        contact_email: "labor.lss@alaska.gov"
    contact:
      phone: "(907) 465-2700"
      email: "labor.lss@alaska.gov"

  arizona:
    name: "Arizona Department of Administration"
    abbreviation: "AZ"
    base_url: "https://azdoa.gov"
    prevailing_wage_url: "https://azdoa.gov/procurement/procurement-policy/prevailing-wages"
    forms:
      - name: "AZ-PW-001"
        title: "Arizona Certified Payroll Report"
        url: "https://azdoa.gov/procurement/procurement-policy/prevailing-wages"
        check_frequency: "weekly"
        contact_email: "prevailingwage@azdoa.gov"
    contact:
      phone: "(602) 542-1500"
      email: "prevailingwage@azdoa.gov"

  arkansas:
    name: "Arkansas Department of Labor and Licensing"
    abbreviation: "AR"
    base_url: "https://www.labor.arkansas.gov"
    prevailing_wage_url: "https://www.labor.arkansas.gov/divisions/labor-standards/prevailing-wage/"
    forms:
      - name: "AR-PW-001"
        title: "Arkansas Certified Payroll Report"
        url: "https://www.labor.arkansas.gov/divisions/labor-standards/prevailing-wage/"
        check_frequency: "weekly"
        contact_email: "prevailingwage@arkansas.gov"
    contact:
      phone: "(501) 682-4500"
      email: "prevailingwage@arkansas.gov"

  california:
    name: "California Department of Industrial Relations"
    abbreviation: "CA"
    base_url: "https://www.dir.ca.gov"
    prevailing_wage_url: "https://www.dir.ca.gov/dlsr/PWD/"
    forms:
      - name: "A1-131"
        title: "California Certified Payroll Report"
        url: "https://www.dir.ca.gov/dlsr/PWD/A1-131.pdf"
        form_url: "https://www.dir.ca.gov/dlsr/PWD/A1-131.pdf"
        instructions_url: "https://www.dir.ca.gov/dlsr/PWD/A1-131-Instructions.pdf"
        check_frequency: "daily"
        contact_email: "askpublicworks@dir.ca.gov"
        last_updated: null
    contact:
      phone: "(415) 703-5070"
      email: "askpublicworks@dir.ca.gov"

  colorado:
    name: "Colorado Department of Labor and Employment"
    abbreviation: "CO"
    base_url: "https://cdle.colorado.gov"
    prevailing_wage_url: "https://cdle.colorado.gov/wage-and-hour-law/prevailing-wage"
    forms:
      - name: "CO-PW-001"
        title: "Colorado Certified Payroll Report"
        url: "https://cdle.colorado.gov/wage-and-hour-law/prevailing-wage"
        check_frequency: "weekly"
        contact_email: "prevailingwage@state.co.us"
    contact:
      phone: "(303) 318-8441"
      email: "prevailingwage@state.co.us"

  connecticut:
    name: "Connecticut Department of Labor"
    abbreviation: "CT"
    base_url: "https://www.ct.gov/dol"
    prevailing_wage_url: "https://www.ct.gov/dol/cwp/view.asp?a=2348&q=334282"
    forms:
      - name: "CT-PW-001"
        title: "Connecticut Certified Payroll Report"
        url: "https://www.ct.gov/dol/cwp/view.asp?a=2348&q=334282"
        check_frequency: "weekly"
        contact_email: "dol.prevailingwage@ct.gov"
    contact:
      phone: "(860) 263-6000"
      email: "dol.prevailingwage@ct.gov"

  delaware:
    name: "Delaware Department of Labor"
    abbreviation: "DE"
    base_url: "https://laborfiles.delaware.gov"
    prevailing_wage_url: "https://laborfiles.delaware.gov/main/lp/prevailing/"
    forms:
      - name: "DE-PW-001"
        title: "Delaware Certified Payroll Report"
        url: "https://laborfiles.delaware.gov/main/lp/prevailing/"
        check_frequency: "weekly"
        contact_email: "prevailingwage@delaware.gov"
    contact:
      phone: "(302) 761-8200"
      email: "prevailingwage@delaware.gov"

  florida:
    name: "Florida Department of Economic Opportunity"
    abbreviation: "FL"
    base_url: "https://www.floridajobs.org"
    prevailing_wage_url: "https://www.floridajobs.org/office-directory/division-of-workforce-services/bureau-of-workforce-statistics-and-economic-research/labor-market-information/employment-and-wage-data/prevailing-wage-rates"
    forms:
      - name: "FL-PW-001"
        title: "Florida Certified Payroll Report"
        url: "https://www.floridajobs.org/office-directory/division-of-workforce-services/bureau-of-workforce-statistics-and-economic-research/labor-market-information/employment-and-wage-data/prevailing-wage-rates"
        check_frequency: "weekly"
        contact_email: "prevailingwage@deo.myflorida.com"
    contact:
      phone: "(850) 245-7105"
      email: "prevailingwage@deo.myflorida.com"

# Note: This is a partial configuration showing the structure. 
# The full implementation would include all 50 states with similar detail.
# For brevity, I'm showing the pattern for the first 10 entries.

monitoring_settings:
  default_check_frequency: "weekly"
  retry_attempts: 3
  timeout_seconds: 30
  user_agent: "PayrollMonitor/1.0 (Government Forms Monitoring)"
  notification_delay_minutes: 5
  backup_frequency: "daily"
  
notification_settings:
  email:
    enabled: true
    smtp_server: "${SMTP_SERVER}"
    smtp_port: 587
    username: "${SMTP_USERNAME}"
    password: "${SMTP_PASSWORD}"
    from_address: "${FROM_EMAIL}"
    to_addresses:
      - "${ALERT_EMAIL_1}"
      - "${ALERT_EMAIL_2}"
  
  slack:
    enabled: false
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "#payroll-alerts"
  
  teams:
    enabled: false
    webhook_url: "${TEAMS_WEBHOOK_URL}"